# BCT Chain Network Status Monitoring Configuration
web:
  port: 8080

storage:
  type: memory

ui:
  title: "BCT Chain Network Status"
  header: "BCT Chain Network Monitoring"

endpoints:
  # BCT Chain Main RPC Endpoint
  - name: bct-rpc-main
    group: rpc-nodes
    url: "https://rpc.bctchain.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    headers:
      Content-Type: application/json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "eth_blockNumber",
        "params": [],
        "id": 1
      }

  # BCT Chain RPC Health Check (GET request)
  - name: bct-rpc-health
    group: rpc-nodes
    url: "https://rpc.bctchain.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200 || [STATUS] == 405"  # RPC endpoints often return 405 for GET requests
      - "[RESPONSE_TIME] < 3000"

  # BCT Chain Block Number Query
  - name: bct-block-query
    group: blockchain-data
    url: "https://rpc.bctchain.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].result != null"
      - "[RESPONSE_TIME] < 5000"
    headers:
      Content-Type: application/json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "eth_blockNumber",
        "params": [],
        "id": 1
      }

  # BCT Chain Network ID Verification
  - name: bct-network-id
    group: blockchain-data
    url: "https://rpc.bctchain.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].result != null"
      - "[RESPONSE_TIME] < 3000"
    headers:
      Content-Type: application/json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "net_version",
        "params": [],
        "id": 1
      }

  # BCT Chain Gas Price Check
  - name: bct-gas-price
    group: blockchain-data
    url: "https://rpc.bctchain.com"
    interval: 2m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].result != null"
      - "[RESPONSE_TIME] < 3000"
    headers:
      Content-Type: application/json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "eth_gasPrice",
        "params": [],
        "id": 1
      }

  # BCT Chain SSL Certificate Monitoring
  - name: bct-ssl-certificate
    group: security
    url: "https://rpc.bctchain.com"
    interval: 6h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 168h"  # Alert if certificate expires within 7 days
      - "[STATUS] == 200 || [STATUS] == 405"

alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK_URL}"
    default-alert:
      description: "BCT Chain RPC issue detected"
      failure-threshold: 3
      success-threshold: 2
